#!/usr/bin/env bash

mkdir tmp
cd tmp

# Downloading trainval2012, trainval2007, test2007
wget pjreddie.com/media/files/VOCtrainval_11-May-2012.tar
wget pjreddie.com/media/files/VOCtrainval_06-Nov-2007.tar
wget pjreddie.com/media/files/VOCtest_06-Nov-2007.tar

# Extract them in tmp folder 
echo "Extracting trainval2012..."
tar -xf VOCtrainval_11-May-2012.tar
mv -v VOCdevkit/VOC2012 ./
rm -r VOCdevkit
echo "Extracting trainval2007..."
tar -xf VOCtrainval_06-Nov-2007.tar
mv -v VOCdevkit/VOC2007 ./
rm -r VOCdevkit
echo "Extracting test2007..."
tar -xf VOCtest_06-Nov-2007.tar
mv -v VOCdevkit/VOC2007 ./VOC2007_Test
rm -r VOCdevkit

# First clean
rm VOCtrainval_11-May-2012.tar
rm VOCtrainval_06-Nov-2007.tar
rm VOCtest_06-Nov-2007.tar
cd ..

# Python script
python voc_preparing.py

# Final clean
rm -r tmp
